# Generated by Django 3.0 on 2022-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='brand_name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptops',
            name='brand_name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiles',
            name='brand_name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
