# Generated by Django 3.0 on 2022-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0003_auto_20220708_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='img',
            field=models.ImageField(upload_to='media/accessories'),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='img',
            field=models.ImageField(upload_to='media/laptops'),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='img',
            field=models.ImageField(upload_to='media/mobiles'),
        ),
    ]
