# Generated by Django 3.0 on 2022-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0004_auto_20220709_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='img',
            field=models.ImageField(upload_to='pro/accessories'),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='img',
            field=models.ImageField(upload_to='pro/laptops'),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='img',
            field=models.ImageField(upload_to='pro/mobiles'),
        ),
    ]
